### ISSUE TITLE
CP4BA storage class should be changed 

### ISSUE THREAD

**Issue by BrahmSingh** [ibm-build-lab/terraform-ibm-cloud-pak#129]
Hi Team,

This is a reference to the **storage class** in following file:  **_modules/cp4ba/templates/cp4a_shared_log_pvc.yaml.tmpl_**. 
The storage class (_**storageClassName: ibmc-file-gold-gid**_) is mentioned as static/hard coded.

 This storage class is not available in any environment and hence we should change it to a dynamic reference storage class.

Update file reference. 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cp4a-shared-log-pvc
  namespace: ${cp4ba_project_name}
  labels:
    app.kubernetes.io/instance: ibm-dba
    app.kubernetes.io/managed-by: ibm-dba
    app.kubernetes.io/name: ibm-dba
    release: 21.0.1
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ${storage_class} 
  resources:
    requests:
      storage: 100Gi

We can make a variable for storage class i.e., ${storage_class}.

**Comment by BrahmSingh** [comment]
@logicJohn @krook 
Could you please review this and update it?

**Comment by BrahmSingh** [comment]
@annumberhocker can you please review this.

**Comment by annumberhocker** [comment]
@BrahmSingh These terraform repos are no longer supported.  They are available as is.

**Comment by pranavibm** [comment]
@annumberhocker , Requesting you to confirm by when above (last week) request of @BrahmSingh will be done. With this we will be able to close current communications. - Thanks in advance.

@logicJohn , @krook , FYI...

**Comment by annumberhocker** [comment]
@pranavibm The changes have been made

> @annumberhocker , Requesting you to confirm by when above (last week) request of @BrahmSingh will be done. With this we will be able to close current communications. - Thanks in advance.
> 
> @logicJohn , @krook , FYI...
